os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: tRqrStduqdH8oV8uQ2YP2JRd83QVB5ibrmnKDXNdPCTw9+Z2TwXoWmPaCrL7fsM5wR04a9d6zy6YqFiEyAu2eXR3tf3Plvd+yl8ZxlaGS4ro3VTed6/XMyySbqHCRQwTtBc/YGi2C9hbjhuQRwwfHlRyujf0grCj7Y+rWqJ2x3UWFIM8wBsePbNcadHB8le2Y4jet5CE4NTiwt+vuWvMNaavODVvZe5Li2gHip2aIQwh5XuxF9W9be1FvOeckco5fIyhdRAh8Dzu05oo/5UgE9Wsbo5kDvgi8E7UnsALgdRgkkPA1m7w6csRvKkebf/X0sOFgg0RLDpaPGoyJ4+M4tlWs82q9+aGGDs8AuvB7MrjtXw8cST/u1uiWIlITZy0SDwJ4rEWbtcvyoqdwq8DjOxiFHMk8iQmYd+WgKtanVx0x5wVsxswvTlyVZA1e8zeGmCEvavf4IJcpPJIUrfxfo6a1fzQE3JxCCgC5zEmihXor/d1FKsTv1DrE/RgTQs92TMEMcvMIy+cbm0te0zISWJKEBtGf2j4tJTHZUnK80+eVC8avEDkqXCLjmlkg2t9d6QXg7Ls5yY1XQSP+pIev8KnthgSnj98AAbikGHS+AX4St/8kvQEaW7Jy4SRALAO9sbhFLUWx0KMu8RSMfm9B7PrzOFamSL/W7NODRW/4+0=
script:
- mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vkgl-clinvar-submission
deploy:
  provider: releases
  token:
    secure: 2MuUGADGLd3LidEuvz44MF+sBPHfYXQlUPNCTvGPUIHZ27mIzO55CuHbJWP4k8t4C6zHXF1kfp9XPQjinqRYfcJT80DLOqxaWKF9YOzey/mEK145s7ygn4TGwgqF69Za8+WKVNbYB/o0z5TTWPNCQBWLJhgO9yNCffyZHOenRCjuQ+ZMj97MOxYBLr4GnMKF9mjPpwE6GwmUE6q7H1NZztmS6//67zw8k+/56BorXNPSnoDiZW4OEGHBT4uudGwIKTRUpTB68iLiGk+0H3jjc8o21MA+GQ8mXXsf6iUv7/ibI3zH5v+GQy5m0TFVLaZp91jrASuNX4rmQuavx5tyFkiShNMNajjbaPaDALEEaX+D8pMTerPG///xp2zG+mqyl0byqJsnXmunGxrcH4Of1qcKVCuccnVEaakotMClif45zesJKs581R87CtUmkMc8WXxfjEqqGoCQekxayTpgBKilZs+jtMNIPecZaMhzBgAsfmTr1bMVfkR0fOCEqtsaKTLMuWNTvmLwdY+40q5BslrCZCO+jAB1r6HdFFAz2N00zDPUY31DXGDmNExaSEvHadowMvPdQ9ArsH4RfwWha5X+CepHZj2GzdGY+AnY5+CobE8w0so6N2kuDGyPzpXVkOVjqzYViZNdkYrA78Bmb19G4MONceZkoLSg1kXExMQ=
  file: target/vkgl-clinvar-submission-writer.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
