os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: NmWApe2n44Mxkb3aQ6Jz3WOdLnXrq067k0LZ7GB2bfU+iL2NmKGODUKYJ3ACWEtuya+Y7wVtUzfqyYl3zx7nxMFgL6JtOijah2zccazfmmNAM2oPV+moax3HVCMsQAMkTFNZU0QGqQ1ZCJr7Ux/Z94681Ak9ABqUsuzcZhF7TczEnFAriJtvxUiivk1ln9+tmQKR/zTDYsOTkgqNBxe5/7KBB0tFJtvBS3/LsCeJLoeQ4+meMDG/QO3NwicBzCPWThF1bjZwVETVKHhtgTmTX6rfEiYc4FgIb3xtIPVN0UGyKTB6NZEtwpiqCg3nUPfAAF1AmgUHLj6PdocTghDq3ssW8IuS02nHPqKOJkDTvFpATkklhYAB+MlaSzQsqJuAq6C2hNgfG4bkr/i3MDAw58Rk8yy9JYUNarkRuCsEYqw5Cio56i604I4mQ6L86hQWSDirCQfMkOs+vAO9OOQC3DOFAJwFEsmmAN3n/d4EElGK/JfJacUGT0oUQRfTSDkMLYUnH8cJ92Smb3u/A98BjguQefnUgh7RUZ9M4KgbmjHaPudwWM8N9CcQ2avblVfNoQ/0HSNvTs+OGC/4zhjbKlNRiG6W96eDv5BPWzzWwPT4pV4qXvthex/9aL8g4ZZ4w+YHA4r4dMUiuRoC0PZ+Ick/69KPFB3N4077zlXGi9Q=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vkgl-clinvar-submission
deploy:
  provider: releases
  token:
    secure: NNLoW1AQGSl3boZ7m+4anjLUUN13gXVI8M7gI4FhHRPyX9bf6zW9MZQfFUl65qJNEJucBHvtxSFyS4KnCk68P9ne1hSQrJtlOCGo8L8Yzi+Ruu+s9a+IxCJUdd4V/RUx4b9+8zxe/XGEv6UZaVBjL8LGb8eif659ONzmQL63Odtp9F8V+WBGMP2otRSQBEF6p9LgA0jMbavkd8L6nkZ28Y8bKQS0fjxlp9AYrUrz/mIDkDJscaAL6mVrZimloO1M4xDQde3ctwC9FzBlv+SjcImrUKSWyrirOL+igCAimxURyU6AGvLrXJY8eolVaEG8r9HbbMtHj6CmgVFYgU3z44nH3IyxQcfil2073RBnapyzmKUXEguLilO5jQbJUX+LSpHzKzpOk3ntimM2eiEOayO7yJzXz14xUEgVkX51G713L+EnhjasVwNsxSAbnJvDiJbOEMeXb5It6TYPl0+HmaPTWuOcrn80z4Fxw1j4qyQ3ZHkW+q6ncE/fWoO9o9QzQgOrG5fWB9xUi2AK1fn0d6EXBit28swBDs9//wrihHasjYSg/ye+GVdw8AS9Ti+ahDaK/EtcHFICfbPd73BxS/sOMVkN4scUaNHzbvpjXIEvKX2ax1dA72Er/89bC3bHuLq+LG0pY4Cu0Ss8bF1Td3vDM7//q4m4VYIJX33YVLE=
  file: target/vkgl-clinvar-submission-writer.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
